services:
  - type: web
    name: goty-the-last-star
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "22"
